// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANNTAo8lebKJTzlrdWtOiAPo6PP6Cy780',
    appId: '1:741438909575:web:e3643f92b094797ded5c22',
    messagingSenderId: '741438909575',
    projectId: 'push-notifications-4c62f',
    authDomain: 'push-notifications-4c62f.firebaseapp.com',
    storageBucket: 'push-notifications-4c62f.appspot.com',
    measurementId: 'G-XGVHF76YW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfpW8KL7wFHNa678HcTMuEzB9KFab97bQ',
    appId: '1:741438909575:android:9161c4da250e1429ed5c22',
    messagingSenderId: '741438909575',
    projectId: 'push-notifications-4c62f',
    storageBucket: 'push-notifications-4c62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCOeX-THTjMv2jomBfge41ATmW0h-dcZE',
    appId: '1:741438909575:ios:4bd74632f0a9e578ed5c22',
    messagingSenderId: '741438909575',
    projectId: 'push-notifications-4c62f',
    storageBucket: 'push-notifications-4c62f.appspot.com',
    iosClientId: '741438909575-112pcmq9l9i50um5ar4uf6vnd3jscekn.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCOeX-THTjMv2jomBfge41ATmW0h-dcZE',
    appId: '1:741438909575:ios:4bd74632f0a9e578ed5c22',
    messagingSenderId: '741438909575',
    projectId: 'push-notifications-4c62f',
    storageBucket: 'push-notifications-4c62f.appspot.com',
    iosClientId: '741438909575-112pcmq9l9i50um5ar4uf6vnd3jscekn.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsApp',
  );
}
